src/IdentityInfo.Web/Areas/Swedish/Models/SwedishCoordinationNumberExtensions.cs
using ActiveLogin.Identity.Swedish;

namespace IdentityInfo.Web.Areas.Swedish.Models
{
    public static class SwedishCoordinationNumberExtensions
    {
        public static char GetDelimiter(this CoordinationNumber swedishCoordinationNumber)
        {
            return swedishCoordinationNumber.To10DigitString()[6];
        }
    }
}

src/IdentityInfo.Web/Areas/Swedish/Models/SwedishCoordinationNumberTestdataListViewModel.cs
using IdentityInfo.Core.Swedish.Requests.CoordinationNumbers;

namespace IdentityInfo.Web.Areas.Swedish.Models
{
    public class SwedishCoordinationNumberTestdataListViewModel
    {
        public SwedishCoordinationNumberTestdataListViewModel(GetTestdataList.Query query, GetTestdataList.Result result)
        {
            Query = query;
            Result = result;
        }

        public GetTestdataList.Query Query { get; }
        public GetTestdataList.Result Result { get; }
    }
}

src/IdentityInfo.Web/Areas/Swedish/Models/SwedishPersonalIdentityNumberTestdataListViewModel.cs
using IdentityInfo.Core.Swedish.Requests.PersonalIdentityNumbers;

namespace IdentityInfo.Web.Areas.Swedish.Models
{
    public class SwedishPersonalIdentityNumberTestdataListViewModel
    {
        public SwedishPersonalIdentityNumberTestdataListViewModel(GetTestdataList.Query query, GetTestdataList.Result result)
        {
            Query = query;
            Result = result;
        }

        public GetTestdataList.Query Query { get; }
        public GetTestdataList.Result Result { get; }
    }
}

src/IdentityInfo.Web/Models/ErrorViewModel.cs
namespace IdentityInfo.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; } = string.Empty;

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/IdentityInfo.Web/Models/GoogleAnalyticsOptions.cs
namespace IdentityInfo.Web.Models
{
    public class GoogleAnalyticsOptions
    {
        public string GoogleAnalyticsKey { get; set; } = string.Empty;
    }
}

src/IdentityInfo.Web/Models/SwedishPersonalIdentityNumberListViewModel.cs
using System.Collections.Generic;
using ActiveLogin.Identity.Swedish;

namespace IdentityInfo.Web.Models
{
    public class SwedishPersonalIdentityNumberListViewModel
    {
        public SwedishPersonalIdentityNumberListViewModel(IEnumerable<SwedishPersonalIdentityNumber> numbers)
        {
            Numbers = numbers;
        }

        public IEnumerable<SwedishPersonalIdentityNumber> Numbers { get; }
    }
}

src/IdentityInfo.Web/Areas/Swedish/Controllers/CoordinationNumberController.cs
using System.Threading.Tasks;
using IdentityInfo.Core.Swedish.Requests.CoordinationNumbers;
using IdentityInfo.Web.Areas.Swedish.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace IdentityInfo.Web.Areas.Swedish.Controllers
{
    [Area(SwedishAreaConfiguration.AreaName)]
    [Route("coordinationnumber")]
    public class CoordinationNumberController : Controller
    {
        private readonly IMediator _meditator;

        public CoordinationNumberController(IMediator meditator)
        {
            _meditator = meditator;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("validate")]
        public async Task<IActionResult> Validate([FromQuery] Validate.Query query)
        {
            if (query.Number != null && query.Number.Length > 50)
            {
                return new BadRequestResult();
            }

            var result = await _meditator.Send(query);
            return View(result);
        }

        [HttpGet("randomize")]
        public async Task<IActionResult> Randomize([FromQuery] Randomize.Query query)
        {
            if (query.Count != null && (query.Count < 1 || query.Count > 10))
            {
                return new BadRequestResult();
            }

            var result = await _meditator.Send(query);
            return View(result);
        }

        [HttpGet("testdata")]
        public async Task<IActionResult> TestDataList([FromQuery] GetTestdataList.Query query)
        {
            if (query.Limit > 1000)
            {
                return new BadRequestResult();
            }

            var result = await _meditator.Send(query);
            var viewModel = new SwedishCoordinationNumberTestdataListViewModel(query, result);
            return View(viewModel);
        }

        [HttpGet("/api/swedish/coordinationnumber/testdata/json")]
        public async Task<IActionResult> TestDataListApi([FromQuery] GetTestdataList.ApiQuery query)
        {
            var result = await _meditator.Send(query);
            return Json(result);
        }
    }
}

src/IdentityInfo.Web/Areas/Swedish/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace IdentityInfo.Web.Areas.Swedish.Controllers
{
    [Area(SwedishAreaConfiguration.AreaName)]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/IdentityInfo.Web/Areas/Swedish/Controllers/PersonalIdentityNumberController.cs
using System.Threading.Tasks;
using IdentityInfo.Core.Swedish.Requests.PersonalIdentityNumbers;
using IdentityInfo.Web.Areas.Swedish.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace IdentityInfo.Web.Areas.Swedish.Controllers
{
    [Area(SwedishAreaConfiguration.AreaName)]
    [Route("personalidentitynumber")]
    public class PersonalIdentityNumberController : Controller
    {
        private readonly IMediator _meditator;

        public PersonalIdentityNumberController(IMediator meditator)
        {
            _meditator = meditator;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("validate")]
        public async Task<IActionResult> Validate([FromQuery] Validate.Query query)
        {
            if (query.Number != null && query.Number.Length > 50)
            {
                return new BadRequestResult();
            }

            var result = await _meditator.Send(query);
            return View(result);
        }

        [HttpGet("randomize")]
        public async Task<IActionResult> Randomize([FromQuery] Randomize.Query query)
        {
            if (query.Count != null && (query.Count < 1 || query.Count > 10))
            {
                return new BadRequestResult();
            }

            var result = await _meditator.Send(query);
            return View(result);
        }

        [HttpGet("testdata")]
        public async Task<IActionResult> TestDataList([FromQuery] GetTestdataList.Query query)
        {
            if (query.Limit > 1000)
            {
                return new BadRequestResult();
            }

            var result = await _meditator.Send(query);
            var viewModel = new SwedishPersonalIdentityNumberTestdataListViewModel(query, result);
            return View(viewModel);
        }

        [HttpGet("/api/swedish/personalidentitynumber/testdata/json")]
        public async Task<IActionResult> TestDataListApi([FromQuery] GetTestdataList.ApiQuery query)
        {
            var result = await _meditator.Send(query);
            return Json(result);
        }
    }
}

src/IdentityInfo.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IdentityInfo.Web.Models;

namespace IdentityInfo.Web.Controllers
{
    public class HomeController : Controller
    {
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            });
        }
    }
}

src/IdentityInfo.Web/Areas/Swedish/Views/CoordinationNumber/Index.cshtml
@{
    ViewBag.Title = "Info & Definition - Swedish Coordination Numbers";
}

<h1 class="h2">
    Info &amp; Definition
    <small class="text-muted">Swedish Coordination Numbers</small>
</h1>

<div class="lead py-3">
    <p>
        The coordination number (samordnignsnummer) is the Swedish national identification number. It is a ten or twelve digit number that is used in Sweden to identify individuals who have any sort of contact with Swedish authorities, but not yet have a Swedish citizenship.
    </p>
</div>


<div class="card mt-2">
    <div class="card-body">
        <h2 class="card-title">Sources</h2>

        <p>
            The definition of a Swedish coordination number is described in Swedish law (Folkbokföringslagen), there are also other sources for clarifications listed below.
        </p>

        <ul>
            <li><a href="https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/folkbokforingslag-1991481_sfs-1991-481#P18a">Folkbokföringslagen (FOL 18a §)</a></li>
            <li><a href="https://www4.skatteverket.se/rattsligvagledning/edition/2019.8/330243.html">Skatteverket (Swedish)</a></li>
            <li><a href="https://www4.skatteverket.se/rattsligvagledning/edition/2019.8/330251.html">Skatteverket (Swedish)</a></li>
            <li><a href="https://www.skatteverket.se/servicelankar/otherlanguages/inenglish/individualsandemployees/livinginsweden/personalidentitynumberandcoordinationnumber.4.2cf1b5cd163796a5c8b4295.html#h-Coordinationnumber">Skatteverket (English)</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Personal_identity_number_(Sweden)#Similar_identity_numbers">Wikipedia (English)</a></li>
        </ul>
    </div>
</div>

src/IdentityInfo.Web/Areas/Swedish/Views/CoordinationNumber/Randomize.cshtml
@using ActiveLogin.Identity.Swedish
@using ActiveLogin.Identity.Swedish.Extensions
@model IdentityInfo.Core.Swedish.Requests.CoordinationNumbers.Randomize.Result;
@{
    ViewBag.Title = "Randomize - Swedish Coordination Numbers";
}

<h1 class="h2">
    Randomize
    <small class="text-muted">Swedish Coordination Numbers</small>
</h1>

<p class="lead py-3">
    Here are @Model.Count random Swedish Coordination Numbers from the list of <a asp-action="TestDataList">testdata</a>.
</p>

<div class="row">
    <div class="col-sm-4">
    </div>
    <div class="col-sm-4">
        <a class="btn btn-primary btn-block" href="#" onclick="location.reload(); return false;">Get @Model.Count new numbers</a>
    </div>
</div>

<div class="row">
    <div class="col-sm">
        <h2 class="h3 mt-3">Numbers</h2>
        <div class="list-group">
            @foreach (var number in Model.Numbers)
            {
                <a href="#pin-@number.To12DigitString()" class="list-group-item list-group-item-action">
                    @number.To10DigitString() <em class="text-muted">(@number.GetAgeHint() year old @(number.GetGenderHint() == Gender.Female ? "female" : "male"))</em>
                </a>
            }
        </div>
    </div>
    <div class="col-sm">
        <h2 class="h3 mt-3">10 digit versions</h2>
<textarea class="form-control" style="min-height: @(49 * Model.Count)px;">@foreach (var number in Model.Numbers)
{
    @number.To10DigitString()
    @Html.Raw("\n")
}</textarea>
    </div>
    <div class="col-sm">
        <h2 class="h3 mt-3">12 digit versions</h2>
<textarea class="form-control" style="min-height: @(49 * Model.Count)px;">@foreach (var number in Model.Numbers)
{
    @number.To12DigitString()
    @Html.Raw("\n")
}</textarea>
    </div>
</div>

<h2 class="h3 mt-4">Details</h2>

@foreach (var number in Model.Numbers)
{
    <div class="mt-4" id="pin-@number.To12DigitString()">
        <partial name="_InfoCard" model="@number" view-data="@(new ViewDataDictionary(ViewData) { { "show-description", true } })" />
    </div>
}

src/IdentityInfo.Web/Areas/Swedish/Views/CoordinationNumber/TestDataList.cshtml
@using ActiveLogin.Identity.Swedish
@using ActiveLogin.Identity.Swedish.Extensions
@model SwedishCoordinationNumberTestdataListViewModel;

@{
    ViewBag.Title = "Testdata - Swedish Coordination Numbers";
}

    <h1 class="h2">
        Testdata
        <small class="text-muted">Swedish Coordination Numbers</small>
    </h1>

<p class="lead py-3">
    Swedish Coordination Numbers should <a href="https://www.datainspektionen.se/other-lang/in-english/the-general-data-protection-regulation-gdpr/sensitive-personal-data/">be treated as personal data</a> and therefore a valid PIN can't be used in scenarios such as testing. For this very purpose Skatteverket has issued a list of testdata with numbers guaranteed not to be given to a person, and they are therefore safe to use. The list below builds upon that orignal list, but enhances it by extracting information such as date of birth, gender and age.
</p>

<form asp-action="TestDataList" method="get">
    <div class="form-row">
        <div class="form-group col-md-6 col-lg-2">
            <label asp-for="Query.DateOfBirth.From">Date of Birth <small class="text-muted">(from)</small></label>
            <input type="date" class="form-control" name="dateofbirth.from" value="@Model.Query.DateOfBirth?.From?.ToString("yyyy-MM-dd")" min="@Model.Result.TotalDateOfBirthRange.From?.ToString("yyyy-MM-dd")" max="@Model.Result.TotalDateOfBirthRange.To?.ToString("yyyy-MM-dd")" title="From @Model.Result.TotalDateOfBirthRange.From?.ToString("yyyy-MM-dd")" />
        </div>
        <div class="form-group col-md-6 col-lg-2">
            <label asp-for="Query.DateOfBirth.To">Date of Birth <small class="text-muted">(to)</small></label>
            <input type="date" class="form-control" name="dateofbirth.to" value="@Model.Query.DateOfBirth?.To?.ToString("yyyy-MM-dd")" min="@Model.Result.TotalDateOfBirthRange.From?.ToString("yyyy-MM-dd")" max="@Model.Result.TotalDateOfBirthRange.To?.ToString("yyyy-MM-dd")" title="To @Model.Result.TotalDateOfBirthRange.To?.ToString("yyyy-MM-dd")" />
        </div>
        <div class="form-group col-md-6 col-lg-2">
            <label asp-for="Query.Age.From">Age <small class="text-muted">(from)</small></label>
            <input type="number" class="form-control" name="age.from" asp-for="Query.Age.From" min="@Model.Result.TotalAgeRange.From?.ToString("D")" max="@Model.Result.TotalAgeRange.To?.ToString("D")" placeholder="@Model.Result.TotalAgeRange.From?.ToString("D")" />
        </div>
        <div class="form-group col-md-6 col-lg-2">
            <label asp-for="Query.Age.To">Age <small class="text-muted">(to)</small></label>
            <input type="number" class="form-control" name="age.to" asp-for="Query.Age.To" min="@Model.Result.TotalAgeRange.From?.ToString("D")" max="@Model.Result.TotalAgeRange.To?.ToString("D")" placeholder="@Model.Result.TotalAgeRange.To?.ToString("D")" />
        </div>
        <div class="form-group col-md-6 col-lg-2">
            <label asp-for="Query.Gender">Gender</label>
            <select class="form-control" name="gender" asp-for="Query.Gender">
                <option value="" selected>All</option>
                <option value="female">Female</option>
                <option value="male">Male</option>
            </select>
        </div>
        <div class="form-group col-md-6 col-lg-2 ii-filter-submit-group">
            <button type="submit" class="btn btn-primary btn-block">Filter</button>
        </div>
    </div>
</form>


@if (Model.Result.FilteredNumbersCount > 0)
{
    if (Model.Query.Limit.HasValue)
    {
        <nav class="d-flex justify-content-between mb-3">
            <partial name="_TestDataListPaginator" model="@Model" />

            <div class="py-1 d-none d-lg-block">
                @if (Model.Result.FilteredNumbersCount == Model.Result.TotalNumbers)
                {
                    <text>Showing all @Model.Result.TotalNumbers.ToString("N0") results.</text>
                }
                else
                {
                    <text>Showing @Model.Result.FilteredNumbersCount.ToString("N0") of @Model.Result.TotalNumbers.ToString("N0") results.</text>
                }
            </div>
        </nav>
    }

    <div class="table-responsive-sm">

        <table class="table table-striped table-hover">
            <thead class="thead-dark thead-sticky">
                <tr>
                    <th scope="col">10 Digit</th>
                    <th scope="col">12 Digit</th>
                    <th scope="col" class="d-none d-lg-table-cell">Year</th>
                    <th scope="col" class="d-none d-lg-table-cell">Month</th>
                    <th scope="col" class="d-none d-lg-table-cell">Day</th>
                    <th scope="col" class="d-none d-lg-table-cell">Coordination day</th>
                    <th scope="col" class="d-none d-lg-table-cell">Delimiter</th>
                    <th scope="col" class="d-none d-lg-table-cell">BirthNumber</th>
                    <th scope="col" class="d-none d-lg-table-cell">Checksum</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Date of Birth</th>
                    <th scope="col">Age</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var number in Model.Result.FilteredNumbers)
                {
                    <tr>
                        <th scope="row">
                            <a asp-action="Validate" asp-route-number="@number.To12DigitString()" title="Show more details">@number.To10DigitString()</a>
                        </th>
                        <td>@number.To12DigitString()</td>
                        <td class="d-none d-lg-table-cell">@number.Year</td>
                        <td class="d-none d-lg-table-cell">@number.Month</td>
                        <td class="d-none d-lg-table-cell">@number.RealDay</td>
                        <td class="d-none d-lg-table-cell">@number.Day</td>
                        <td class="d-none d-lg-table-cell">@number.GetDelimiter()</td>
                        <td>
                            <i class="fal fa-@(number.GetGenderHint() == Gender.Female ? "venus" : "mars")" title="@number.GetGenderHint()"></i>
                            @number.GetGenderHint()
                        </td>
                        <td>@number.GetDateOfBirthHint()?.ToString("yyyy-MM-dd")</td>
                        <td>@(number.GetAgeHint()?.ToString("D"))</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="alert alert-info" role="alert">
        No results matched the current filter.
    </div>
}

src/IdentityInfo.Web/Areas/Swedish/Views/CoordinationNumber/Validate.cshtml
@model IdentityInfo.Core.Swedish.Requests.CoordinationNumbers.Validate.Result;
@{
    ViewBag.Title = "Validate - Swedish Coordination Numbers";
}

<h1 class="h2">
    Validate
    <small class="text-muted">Swedish Coordination Numbers</small>
</h1>

<p class="lead py-3">
    A Swedish coordination number can be written in a lot of different ways. It normally takes one of the standard forms (YYMMDD-BBBC, YYMMDD+BBBC or YYYYMMDDBBBC) but can also include variations with whitespaces etc. Use the form below to parse a value and find out data that be extracted form the number such as date of birth and gender.
</p>


<section class="card bg-white text-center mb-3">
    <div class="card-body py-5">
        <div style="max-width: 400px; margin: 0 auto;">
            <form asp-action="Validate" method="get">
                <div class="form-group">
                    <label asp-for="NumberInput">Swedish Coordination Number</label>
                    <input type="tel" class="form-control form-control-lg text-center" name="number" asp-for="NumberInput" required maxlength="50" placeholder="YYMMDD-XXXX" />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Validate</button>
                </div>
            </form>
        </div>
    </div>
</section>

@if (!string.IsNullOrEmpty(Model.NumberInput))
{
    if (Model.IsValid)
    {
        if (!Model.IsTestdataNumber)
        {
            <div class="alert alert-success text-center" role="alert">
                <i class="fal fa-badge-check"></i> <strong>@Model.NumberInput</strong> is recognized as a valid Swedish Coordination Number!
            </div>
        }
        else
        {
            <div class="alert alert-warning text-center" role="alert">
                <i class="fal fa-exclamation-triangle"></i> <strong>@Model.NumberInput</strong> is recognized as a valid Swedish Coordination Number!<br />
                <strong>Note:</strong> It is found in the list of <a asp-action="TestDataList">testdata</a> that is forbidden to use in production!
            </div>
        }

        if (Model.IsValid)
        {
            <partial name="_InfoCard" model="@Model.Number" view-data="@(new ViewDataDictionary(ViewData) { { "show-description", true } })" />
        }
    }
    else
    {
<div class="alert alert-danger text-center" role="alert">
    <i class="fal fa-exclamation-square"></i> <strong>@Model.NumberInput</strong> is not recognized as a valid Swedish Coordination Number!
    <p>
        Details: @Model.InvalidReason
    </p>
</div>
    }
}

src/IdentityInfo.Web/Areas/Swedish/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1 class="text-center">Swedish Identity Info</h1>

<section class="card bg-white text-center mb-5">
    <div class="card-body py-5">
        <p class="card-text lead">
            Swedish Identity Info is a site that aims to provide info and data regarding identities in Sweden like Personal Identity Number (personnummer) and Coordination Number (samordningsnummer).
        </p>
    </div>
</section>


<section class="mb-5">
    <h2 class="text-center mb-5">Swedish Personal Identity Number</h2>

    <div class="card-deck">
        <div class="card">
            <div class="card-body ii-card-button-bottom">
                <h5 class="card-title">Info &amp; Definition</h5>
                <p class="card-text">Read about how a personal identity number is defined and more info about the structure.</p>
                <a class="btn btn-primary ii-card-button-bottom" asp-area="Swedish" asp-controller="PersonalIdentityNumber" asp-action="Index">Read more</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body ii-card-button-bottom">
                <h5 class="card-title">Randomize</h5>
                <p class="card-text">Randomize a valid personal identity number safe from the testdata.</p>
                <a class="btn btn-primary ii-card-button-bottom" asp-area="Swedish" asp-controller="PersonalIdentityNumber" asp-action="Randomize">Randomize</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body ii-card-button-bottom">
                <h5 class="card-title">Validate</h5>
                <p class="card-text">Validate whether or not a specific number is a valid personal identity number.</p>
                <a class="btn btn-primary ii-card-button-bottom" asp-area="Swedish" asp-controller="PersonalIdentityNumber" asp-action="Validate">Validate</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body ii-card-button-bottom">
                <h5 class="card-title">Testdata</h5>
                <p class="card-text">List of tesdata that provides GDPR complient personal identity numbers for non existing persons.</p>
                <a class="btn btn-primary ii-card-button-bottom" asp-area="Swedish" asp-controller="PersonalIdentityNumber" asp-action="TestDataList">View testdata</a>
            </div>
        </div>
    </div>
</section>

<section class="mb-5">
    <h2 class="text-center mb-5">Swedish Coordination Number</h2>

    <div class="card-deck">
        <div class="card">
            <div class="card-body ii-card-button-bottom">
                <h5 class="card-title">Info &amp; Definition</h5>
                <p class="card-text">Read about how a coordination number is defined and more info about the structure.</p>
                <a class="btn btn-primary ii-card-button-bottom" asp-area="Swedish" asp-controller="CoordinationNumber" asp-action="Index">Read more</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body ii-card-button-bottom">
                <h5 class="card-title">Randomize</h5>
                <p class="card-text">Randomize a valid coordination number safe from the testdata.</p>
                <a class="btn btn-primary ii-card-button-bottom" asp-area="Swedish" asp-controller="CoordinationNumber" asp-action="Randomize">Randomize</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body ii-card-button-bottom">
                <h5 class="card-title">Validate</h5>
                <p class="card-text">Validate whether or not a specific number is a valid coordination number.</p>
                <a class="btn btn-primary ii-card-button-bottom" asp-area="Swedish" asp-controller="CoordinationNumber" asp-action="Validate">Validate</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body ii-card-button-bottom">
                <h5 class="card-title">Testdata</h5>
                <p class="card-text">List of tesdata that provides GDPR complient coordination numbers for non existing persons.</p>
                <a class="btn btn-primary ii-card-button-bottom" asp-area="Swedish" asp-controller="CoordinationNumber" asp-action="TestDataList">View testdata</a>
            </div>
        </div>
    </div>
</section>


<h2 class="text-center mb-2 mt-5">Credits</h2>

<section class="card bg-white text-center mb-5">
    <div class="card-body">
        <p class="lead">
            Swedish Personal Identity Number is created by <a href="https://twitter.com/PeterOrneholm">Peter Örneholm</a> as a hobby project to share info about swedish identities while exploring open source, Azure and other technologies :)
        </p>

        <p class="lead">
            Swedish Personal Identity Number is dependent on <a href="https://github.com/ActiveLogin/ActiveLogin.Identity">ActiveLogin.Identity</a> for parsing, normalizing and extracting info out of the identity numbers. Thanks <a href="https://twitter.com/PeterOrneholm">Peter Örneholm</a> and <a href="https://twitter.com/Emmet_Ray">Viktor Andersson</a> who are the main contributors of that.
        </p>

        <p class="lead">
            All <a href="https://github.com/PeterOrneholm/identityinfo.net">source code is available on GitHub</a>, feel free to do a PR or file an Issue if you have feedback!
        </p>
    </div>
</section>

src/IdentityInfo.Web/Areas/Swedish/Views/Shared/_Layout.cshtml
@{
    Layout = "_MasterLayout";
    ViewData["Subsite"] = "Swedish";
}

@section Scripts {
    @RenderSection("Scripts", required: false)
}
@section Styles {
    @RenderSection("Styles", required: false)
}

@section Leftmenu {
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link nav-link-header" asp-area="Swedish" asp-controller="PersonalIdentityNumber" asp-action="Index">Personal Identity Number</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Swedish" asp-controller="PersonalIdentityNumber" asp-action="Index">Info &amp; Definition</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Swedish" asp-controller="PersonalIdentityNumber" asp-action="Randomize">Randomize</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Swedish" asp-controller="PersonalIdentityNumber" asp-action="Validate">Validate</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Swedish" asp-controller="PersonalIdentityNumber" asp-action="TestDataList">Testdata</a>
        </li>


        <li class="nav-item">
            <a class="nav-link nav-link-header" asp-area="Swedish" asp-controller="CoordinationNumber" asp-action="Index">Coordination Number</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Swedish" asp-controller="CoordinationNumber" asp-action="Index">Info &amp; Definition</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Swedish" asp-controller="CoordinationNumber" asp-action="Randomize">Randomize</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Swedish" asp-controller="CoordinationNumber" asp-action="Validate">Validate</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Swedish" asp-controller="CoordinationNumber" asp-action="TestDataList">Testdata</a>
        </li>
    </ul>
}

@RenderBody()